### PR TITLE
Added README.md [CI SKIP]

### PR DESCRIPTION
**Pull request by hwittenborn**
We'll make the CI images republish nightly shortly.

### CODE REVIEW

**Comment by hwittenborn** [comment]
Should we add a note that external users shouldn't pull/use these images since they're only designed to be used in the CI?

**Comment by lpuv** [comment]
> Should we add a note that external users shouldn't pull/use these images since they're only designed to be used in the CI?

Yes.

**Review by lpuv — APPROVED** [review]
LGTM

**Comment by hwittenborn** [comment]
Alright, let's get 'er merged :)

**Pull request merged**
